//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.EIEC.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ICEResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ICEResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.EIEC.Model.ICEResource", typeof(ICEResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add Adjustment. Please try again or contact the administrator..
        /// </summary>
        public static string AdjustmentsAddedFailed {
            get {
                return ResourceManager.GetString("AdjustmentsAddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment have been added sucessfully..
        /// </summary>
        public static string AdjustmentsAddedSuccess {
            get {
                return ResourceManager.GetString("AdjustmentsAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Adjustments data. Please try again or contact the administrator..
        /// </summary>
        public static string AdjustmentsLoadingFailed {
            get {
                return ResourceManager.GetString("AdjustmentsLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load Adjustments Templates. Please try again or contact the administrator..
        /// </summary>
        public static string AdjustmentsTemplatesLoadingFailed {
            get {
                return ResourceManager.GetString("AdjustmentsTemplatesLoadingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to clone algorithm. Please try again..
        /// </summary>
        public static string ConfigAlgorithmClonedError {
            get {
                return ResourceManager.GetString("ConfigAlgorithmClonedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm not saved/updated. Please try again..
        /// </summary>
        public static string ConfigAlgorithmError {
            get {
                return ResourceManager.GetString("ConfigAlgorithmError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faield to save the query. Please try again..
        /// </summary>
        public static string ConfigQueryError {
            get {
                return ResourceManager.GetString("ConfigQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule not Saved / Updated. Please try again..
        /// </summary>
        public static string ConfigRuleError {
            get {
                return ResourceManager.GetString("ConfigRuleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Id was not found..
        /// </summary>
        public static string ExclusionIdNotFound {
            get {
                return ResourceManager.GetString("ExclusionIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Status has been updated..
        /// </summary>
        public static string JobUpdatedMessage {
            get {
                return ResourceManager.GetString("JobUpdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Configuration Rule created..
        /// </summary>
        public static string NewConfigRuleMessage {
            get {
                return ResourceManager.GetString("NewConfigRuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add new Task. Please try again or contact the administrator..
        /// </summary>
        public static string NewTaskAddedFailed {
            get {
                return ResourceManager.GetString("NewTaskAddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task have been added/updated sucessfully..
        /// </summary>
        public static string NewTaskAddedSuccess {
            get {
                return ResourceManager.GetString("NewTaskAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes found..
        /// </summary>
        public static string NoChange {
            get {
                return ResourceManager.GetString("NoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set preview flag. Please try again or contact the administrator..
        /// </summary>
        public static string PaymentPreviewFailed {
            get {
                return ResourceManager.GetString("PaymentPreviewFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview flag set successfully..
        /// </summary>
        public static string PaymentPreviewSuccess {
            get {
                return ResourceManager.GetString("PaymentPreviewSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more required value is missing..
        /// </summary>
        public static string RequiredValueMissing {
            get {
                return ResourceManager.GetString("RequiredValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules have been added to the list..
        /// </summary>
        public static string RuleMessage {
            get {
                return ResourceManager.GetString("RuleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been saved..
        /// </summary>
        public static string SaveDataMessage {
            get {
                return ResourceManager.GetString("SaveDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated existing Configuration Rule..
        /// </summary>
        public static string UpdateConfigRuleMessage {
            get {
                return ResourceManager.GetString("UpdateConfigRuleMessage", resourceCulture);
            }
        }
    }
}
